development: &development
  adapter: postgresql
  encoding: unicode
  database: wbooks_development
  host: localhost
  port: 5432
  pool: 5
  username: wbooks-api
  password: wbooks-api

test:
  <<: *development
  database: wbooks_test
